adds tests to ensure that gds files with frozen timestamps have consistent hashes
heitzmann/gdspy pull request #180
Opened 2021-06-04 09:44 UTC by tvt173

This PR adds new tests to ensure that 
1. GDS files with different timestamps have different hashes
2. GDS files with identical timestamps have identical hashes
    - when empty
    - with cells
    - with cell arrays

2021-06-04 10:58 UTC, heitzmann requested changes
Btw, great naming scheme :smile:

2021-06-04 10:58 UTC, heitzmann commented on tests/cell.py
> +import pathlib
This import breaks Python 2.7. We should not use `pathlib`.

2021-06-04 10:58 UTC, heitzmann commented on tests/cell.py
> +tmpdir = pathlib.Path(__file__).parent / 'tmp'
Use [`tmpdir` from pytest](https://docs.pytest.org/en/6.2.x/tmpdir.html#the-tmpdir-fixture) instead. Take a look at the tests for [`GdsLibrary`](https://github.com/heitzmann/gdspy/blob/master/tests/gdslibrary.py) or [`GdsWriter`](https://github.com/heitzmann/gdspy/blob/master/tests/gdswriter.py) for examples.

2021-06-04 12:20 UTC, tvt173 commented
Thanks @heitzmann . I made the requested changes and moved these tests under `gdswriter` instead of `cell` (though in retrospect, maybe `gdslibrary` would have been more appropriate?)

Anyways, it should all be working now. Please merge and release when you are ready. Looking forward to these updates...

p.s. I was also thinking it would be nice to have a quick utility to update all timestamps in an existing file to a given value... ideally by just reading and rewriting the bytes, without taking time to convert into a library and back. I took a quick stab and failed. If you have a good idea on how to achieve this, it would be a nice addition. Otherwise I may take a another look on another day :)

2021-06-05 01:33 UTC, heitzmann commented
Yes, with `GdsLibrary` would be a better place for those. Would you mind moving the tests to that file?

As for the timestamp update, I guessing something like this should work (I haven't tested it):

```python
def set_timestamp(filename, timestamp):
    ts = struct.pack(
        ">12h",
        now.year,
        now.month,
        now.day,
        now.hour,
        now.minute,
        now.second,
        now.year,
        now.month,
        now.day,
        now.hour,
        now.minute,
        now.second,
    )
    ## For compatibility
    # if hasattr(filename, "__fspath__"):
    #     filename = filename.__fspath__()
    with open(filename, "r+b") as fio:
        while True:
            data = fio.read(4)
            if len(data) < 4:
                if len(data) > 0:
                    warnings.warn("Possibly corrupted file", stacklevel=2)
                return
            size, rec_type = struct.unpack(">HH", header)
            if rec_type == 0x0102 or rec_type == 0x0502:
                assert size == 28
                fio.write(ts)
            else:
                fio.seek(size - 4, 1)
```

2021-06-08 11:08 UTC, heitzmann approved these changes

2021-06-08 11:08 UTC, merged